swagger: '2.0'
info:
  title: Python Web
  description: >-
    This is a sample server Petstore server. For this sample, you can
    use the api key `special-key` to test the authorization filters.
  contact:
    email: liuyuanhui@founder.com.cn
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
host: 'python-web.test.fzyun.io'
tags:
  - name: report
    description: Upload test result
paths:
  /report:
    post:
      tags:
        - report
      summary: uploads test result
      operationId: uploadResult
      consumes: 
        - "multipart/form-data"
      parameters:
        - name: buildUrl
          in: query
          description: Current url on Jenkins
          required: true
          type: string
        - name: file
          in: formData
          description: file to upload
          required: true
          type: file
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      tags:
        - report
      summary: get test result
      operationId: getResult
      responses:
        '200':
          description: successful operation
          schema:
            type: string
definitions:
  ApiResponse:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
